BasicUnderstandingFlask/models.py
# from model_intialize import db
from sqlalchemy.ext.hybrid import hybrid_property
from BasicUnderstandingFlask import db,login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash,check_password_hash

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model,UserMixin):

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(100))

    def __repr__(self):
        return self.username
    
    def __init__(self,username,email,password):
        self.username=username
        self.email=email
        self.password=generate_password_hash(password)

    def check_password(self,passw):
        return(check_password_hash(self.password,passw))
    @hybrid_property
    def get_email(self):
        return self.email


# associateTable=db.table(
#     db.Column("post_id",db.Integer,db.ForeignKey("post.id")),
#     db.Column("comments_id",db.Integer,db.ForeignKey("comments.id"))
# )

class Post(db.Model):

    id=db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(100),nullable=False)
    description = db.Column(db.String(500),nullable=False)
    user_id= db.Column(db.Integer,db.ForeignKey('user.id'))
    users=db.relationship('User',backref="posts",lazy=True)
    # comments=db.relationship('comments',secondary="associateTable",lazy=True,
    #                         backref=db.backref('posts', lazy=True))

    def __repr__(self):
        return self.title



class comments(db.Model):
    id=db.Column(db.Integer,primary_key=True)
    comments_description=db.Column(db.String(150),nullable=False)

    def __repr__(self):
        return self.comments_description[20]

BasicUnderstandingFlask/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,PasswordField,TextAreaField
# from wtforms.fields.html5 import EmailField or commonly use stringfield with email as validators
from wtforms.validators import (input_required,
                                Email,
                                length,
                                regexp,
                                optional,
                                EqualTo,
                                ValidationError
                                )

class MyFirstBasicForm(FlaskForm):
    Name=StringField("How do i call you!",validators=[input_required()])
    Email=StringField("Can i have your Email",validators=[Email(message="Please enter valid Email Address")])
    password=PasswordField("Password",validators=[length(min=8,max=16,message="Password must be 8-16 characters"),
                                            regexp(r"^[a-zA-Z0-9!@#$]+$",message="Regex failed")])
    confirmpassword=PasswordField("confirm password",validators=[EqualTo('password',message="Passwords are not matched")])

    def validate_Name(self,field):
        if(len(field.data)<5):
            raise ValidationError("Enter a name not a nickname with lesser charaters")

class postform(FlaskForm):
    title=StringField("Title of the Post",validators=[input_required()])
    description=TextAreaField("Description of the Post",validators=[input_required()])

    def validate_description(self,field):
        if len(field.data)<10:
            return ValidationError("Description is too short to post")

BasicUnderstandingFlask/__init__.py
from flask import Flask,Blueprint
from flask_migrate import Migrate
import os
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

app=Flask(__name__)
app.config["SECRET_KEY"]="Chivo"
Base_Dir=os.path.abspath(os.path.dirname(__file__))
app.config["SQLALCHEMY_DATABASE_URI"]="sqlite:///"+os.path.join(Base_Dir,'sqlite.db')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)
Migrate(app,db)
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view="basics.Flasklogin"
from BasicUnderstandingFlask.views import basic_buleprint
app.register_blueprint(basic_buleprint,url_prefix='/blueprint')

BasicUnderstandingFlask/views.py
from flask import Flask,render_template,url_for,request,redirect,make_response,session,Blueprint,current_app
from .forms import MyFirstBasicForm,postform
from BasicUnderstandingFlask import db,app
from .models import User,comments,Post
from flask_login import login_required,login_user,logout_user

basic_buleprint= Blueprint("basics",__name__,
                            template_folder='templates\FlaskBasics')
with app.app_context():
    print(dir(app))
    print(app.blueprints)
    print(current_app)
    print(current_app.name)
# def create():
#     # p1=Post(title="Sriram's blog",description="sriram@dvb.com is his email")
#     # user1=User.query.get(1)
#     # print(user1.id)
#     # p1.user_id=user1.id
#     p1=User("Chivothboss","Chivo0007@gmail.com","Chivo@07")
#     db.session.add(p1)
#     db.session.commit()
#     return "Success"
# create()

# print(User.query.filter_by(username="Chivothboss")[0].password)
 
@basic_buleprint.route("/signin",methods=['GET','POST'])
def Flasklogin():
    if request.method=="POST":
        username=request.form.get("username")
        password=request.form.get("password")
        try:
            user=User.query.filter_by(username=username)[0]
            if user.check_password(password):
                login_user(user)
                nexturl=request.args.get("next")
                return redirect(nexturl or url_for("basics.showallposts",name=user.username))
        except:
            return redirect(url_for("basics.signup"))
    return render_template("signin.html")
    # # u1=User.query.get(1)
    # login_user(u1)
    # resp=make_response(redirect(url_for("basics.start",fname=u1.username)))
    # resp.set_cookie('username',u1.username)
    # return resp

@basic_buleprint.route("/signout",methods=['GET','POST'])
def logout():
    logout_user()
    return "Logged Out Successfully"

@basic_buleprint.route("/signup",methods=['GET','POST'])
def signup():
    form=MyFirstBasicForm()
    if request.method=="POST":
        if form.validate_on_submit():
            fname=form.Name.data
            session["name"]=fname
            session["email"]=form.Email.data
            u=User(username=fname,email=form.Email.data,password=form.password.data)
            db.session.add(u)
            db.session.commit()
            return redirect(url_for("basics.start",fname=fname))
        else:
            pass
    resp=make_response(render_template("signup.html",form=form))
    resp.set_cookie('username', 'the username')
    return resp


@basic_buleprint.route("/start/<string:fname>",methods=['GET','POST'])
@login_required
def start(fname):
    try:
        print(request.cookies.get("username"))
        # print(session["user_id"])
        print(session)
        print(session["_user_id"])
    except:
        pass
    if request.method=="POST":
        list_of_ans=request.form.getlist("lang")
        print(list_of_ans)
    return render_template("welcome.html",name=fname)
@basic_buleprint.route("/save" , methods=['GET'])
def save():
    return url_for("home")

@basic_buleprint.route("/<string:name>/allposts",methods=['GET','POST'])
@login_required
def showallposts(name):
    form=postform()
    if request.method=="POST":
        if form.validate_on_submit():
            title=form.title.data
            description=form.description.data
            getuserid=User.query.filter(User.username==name)[0].id
            p=Post(title=title,description=description,user_id=getuserid)
            db.session.add(p)
            db.session.commit()
            form.description.data=''
            form.title.data=''
        else:
            print(form.errors)
    getallposts=Post.query.all()
    # print(getallposts)
    return render_template("allposts.html",allposts=getallposts,form=form)


#-----------FOr understanding ----------------


# print(User.query.filter_by(username="Flask1"))
# users=User.query.all()[0]
# print(users.password)
# user1=User.query.get(1)
# print(user1)
# random=user1.posts[0].description
# random=User.query.join(Post).all()
# print(random)

BasicUnderstandingFlask/templates/FlaskBasics/allposts.html
{% include 'base.html' %}
    <div class="container">
        <div class="container my-3">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <form action="" method="POST">
                        {{ form.hidden_tag() }}
                        <div class="form-group">
                            <label for="exampleInputEmail1">{{form.title.label}}</label>
                            {{form.title(class="form-control")}}
                          </div>
                        {% if form.title.errors %}
                        {{form.title.errors}}
                        {% endif %}
                        <br>
                        <div class="form-group">
                            <label for="exampleInputEmail1">{{form.description.label}}</label>
                            {{form.description(class="form-control")}}
                          </div>
                        {% if form.description.errors %}
                        {{form.description.errors}}
                        {% endif %}
                        <input type="submit" value="post" class="btn btn-primary">
                    </form>
                </div>
            </div>
        </div>
        <div class="jumbotron my-3">
            <h3 class="display-4 my-1 text-center">
                All Posts
            </h3>
            <ul>
            {% for posts in allposts %}

                    <li>
                        {{posts.title}}
                    </li>
                    <li>
                        {{posts.description}}
                    </li>
                    <li>
                        Posted by : {{posts.users.get_email}}
                    </li>
                    <hr class="text-light">
            {% endfor %}
            </ul>
        </div>
    </div>

BasicUnderstandingFlask/templates/FlaskBasics/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
  </head>
  <body>
    <!-- Image and text -->
<nav class="navbar navbar-light bg-primary">
    <a class="navbar-brand"  href="{{ url_for('home') }}">
      <img src="../../static/man.png" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
      <span class="text-light lead">FlaskMan</span> 
    </a>
    <ul class="navbar-nav ml-auto">
    <li class="nav-item ml-auto">
      <a class="nav-link px-3 text-light" href="{{ url_for('basics.logout') }}">Logout!</a>
      </li>
    </ul>
  </nav>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

BasicUnderstandingFlask/templates/FlaskBasics/home.html
{% include 'base.html'%}

<html>
<head>
    <title>
        Meet Mr:Flask
    </title>
</head>
    
<div class="container">
    <div class="jumbotron text-center bg-dark my-4 animate__animated animate__lightSpeedInRight">
        <p class="lead text-light">
                Hello Boys and Girls ! Welcome to meet FlaskMan!!!!
        </p>
        <hr class="bg-light">
        <p class="lead text-light">
            Do you like to meet FlaskMan?
        </p>
<a href="{{ url_for('basics.signup') }}" class="btn btn-sm btn-primary">SignUp</a>
        <hr class="bg-light">
        <p class="lead text-light">
            Already Met FlaskMan?
        </p>
        <a href="" class="btn btn-sm btn-primary">SignIn</a>
    </div>
</div>
    
</html>

BasicUnderstandingFlask/templates/FlaskBasics/signin.html
{% include 'base.html' %}

<div class="container">
    <form action="{{ url_for('basics.Flasklogin') }}" method="POST">
        <div class="form-group">
          <label for="exampleInputEmail1">username</label>
          <input type="text" class="form-control" id="exampleInputEmail1" name="username" aria-describedby="emailHelp" placeholder="Enter username">
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Password">
        </div>
        <div class="form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
</div>

BasicUnderstandingFlask/templates/FlaskBasics/signup.html
{% include 'base.html' %}

<div class="container">
    <div class="container m-sm-1 m-md-2 m-lg-3 m-xl-4">
        <form class="m-3 p-3" method="POST">
          {{ form.hidden_tag() }}
            <div class="form-group">
              <label for="formGroupExampleInput">{{form.Name.label}}</label>
              <!-- <input type="text" class="form-control" name= "fname" id="formGroupExampleInput" placeholder="Enter First Name"> -->
              {{form.Name(class="form-control")}}
              {% if form.Name.errors %}
              <ul class="text-danger">
                {% for error in form.Name.errors %}
                  <li>{{ error }}</li>
                  {% endfor %}
              </ul>
          {% endif %}
            </div>
            <div class="form-group">
                <label for="formGroupExampleInput2">{{form.Email.label}}</label>
                <!-- <input type="text" class="form-control" name="email" id="formGroupExampleInput2" placeholder="Enter Email Address"> -->
                {{form.Email(class="form-control")}}
                {% if form.Email.errors %}
                <ul class="text-danger">
                  {% for error in form.Email.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
              </div>
              <div class="form-group">
                <label for="formGroupExampleInput2">{{form.password.label}}</label>
                <!-- <input type="text" class="form-control" name="pwd" id="formGroupExampleInput2" placeholder="Password"> -->
                {{form.password(class="form-control")}}
                {% if form.password.errors %}
                <ul class="text-danger">
                  {% for error in form.password.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
              </div>
              <div class="form-group">
                <label for="formGroupExampleInput2">{{form.confirmpassword.label}}</label>
                <!-- <input type="text" class="form-control" name="pwd1" id="formGroupExampleInput2" placeholder="Confirm Password"> -->
                {{form.confirmpassword(class="form-control")}}
                {% if form.confirmpassword.errors %}
                <ul class="text-danger">
                  {% for error in form.confirmpassword.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
              </div>
              <div class="text-center">
                  <input type="submit" href="" class="btn btn-lg btn-primary py-2" value=" Meet FlaskMan!">
                     
              </div>
          </form>
    </div>
</div>

BasicUnderstandingFlask/templates/FlaskBasics/welcome.html
{% include 'base.html' %}

<div class="container">
    <div class="jumbotron my-3">
        <h6 class="text-success border border-dark my-3 p-2">
            Welcome <span class="ont-weight-bold text-primary">{{name}}</span> , One more step to be completed to meet flaskman!!!!
        </h6>

        <div class="container my-2">
            <p class="lead font-weight-bold my-3">
                Below topics FlaskMan can answer, Please choose one or more you intrested
            </p>
            <form action="" method="POST">
                <div class="form-check">
                    <input class="form-check-input" name="lang" type="checkbox" value="Python" id="defaultCheck1">
                    <label class="form-check-label" for="defaultCheck1">
                    Python
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" name="lang" type="checkbox" value="Django" id="defaultCheck1">
                    <label class="form-check-label" for="defaultCheck1">
                    Django
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" name="lang" type="checkbox" value="Flask" id="defaultCheck1">
                    <label class="form-check-label" for="defaultCheck1">
                    Flask
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" name="lang" type="checkbox" value="Fast Api" id="defaultCheck1">
                    <label class="form-check-label" for="defaultCheck1">
                        Fast Api
                    </label>
                </div>
                <input class="btn btn-sm btn-primary my-3" type="Submit" value="Go!">
            </form>
        </div>
        
    </div>
</div>

BasicUnderstandingFlask/templates/home.html
{% include 'base.html'%}

<html>
<head>
    <title>
        Meet Mr:Flask
    </title>
</head>
    
<div class="container">
    <div class="jumbotron text-center bg-dark my-4 animate__animated animate__lightSpeedInRight">
        <p class="lead text-light">
                Hello Boys and Girls ! Welcome to meet FlaskMan!!!!
        </p>
        <hr class="bg-light">
        <p class="lead text-light">
            Do you like to meet FlaskMan?
        </p>
        <a href="{{ url_for('signup') }}" class="btn btn-sm btn-primary">SignUp</a>
        <hr class="bg-light">
        <p class="lead text-light">
            Already Met FlaskMan?
        </p>
        <a href="" class="btn btn-sm btn-primary">SignIn</a>
    </div>
</div>
    
</html>